[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79

[tool.black]
line-length = 79

[tool.pytest.ini_options]
console_output_style = "count"
minversion = "7.0"
testpaths = ["fillers/example"]
python_files = "*.py"